In [ ]:
#1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde
#güncelleyip 2 boyutlu hale getirin.


In [3]:
import numpy as np

In [2]:
np.arange(30).reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [ ]:
#2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu
#hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [4]:
arr=np.random.randint(0,100,60).reshape(3,5,-1)
arr

array([[[82, 54, 90, 20],
        [11, 14, 45, 49],
        [37, 73, 36, 79],
        [20, 30, 88,  9],
        [55, 63, 68, 99]],

       [[59, 67, 93,  1],
        [81, 78, 52, 23],
        [ 0, 85, 31, 65],
        [72, 61,  5, 86],
        [28, 48, 55, 40]],

       [[98, 21, 60, 89],
        [33, 13, 24,  2],
        [99, 59,  3, 21],
        [21, 97, 62, 56],
        [72, 65,  6,  6]]])

In [7]:
arr.shape

(3, 5, 4)

In [8]:
arr.ndim

3

In [ ]:
#3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale 
#getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [10]:
arr=np.random.randint(0,50,(4,5))
arr

array([[ 4, 24, 23, 16, 26],
       [43, 48, 40, 13, 44],
       [15, 41, 40, 24, 43],
       [28, 31, 31, 21, 49]])

In [11]:
arr=arr.reshape(-1)

In [14]:
arr.shape

(20,)

In [15]:
arr.ndim

1

In [ ]:
#4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün 
#elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.


In [16]:
arr2d=np.random.randint(0,50,(3,3))
arr2d

array([[15, 20, 29],
       [29, 30, 43],
       [41, 49, 14]])

In [17]:
for x in arr2d:
    for y in x:
        print(y)

15
20
29
29
30
43
41
49
14


In [18]:
 for x in np.nditer(arr2d):
     print(x)

15
20
29
29
30
43
41
49
14


In [ ]:
#5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   #1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
  # Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın.(toplansın/çıkartılsın/çarpılsın/bölünsün gibi.)


In [19]:
arr_1=np.arange(5,31,5)
arr_2=np.arange(1,7)
print(arr_1)
print(arr_2)

[ 5 10 15 20 25 30]
[1 2 3 4 5 6]


In [114]:
print(arr_1+arr_2)
print(arr_1-arr_2)
print(arr_1*arr_2)
print(arr_1/arr_2)

[ 6 12 18 24 30 36]
[ 4  8 12 16 20 24]
[  5  20  45  80 125 180]
[5. 5. 5. 5. 5. 5.]


In [ ]:
#6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.


In [28]:
calc_ar=np.random.randint(0,100,10)
calc_ar

array([14, 59, 19, 45, 31, 47, 50, 61, 50, 40])

In [31]:
print(np.sum(calc_ar))
print(np.mean(calc_ar))
print(np.max(calc_ar))
print(np.var(calc_ar))
print(np.std(calc_ar))

416
41.6
61
224.84
14.994665718181249


In [ ]:
#7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. 
#Ardından bu iki array'i concatenate ederek ekrana yazdırın.


In [20]:
ar_1=np.arange(0,20)
ar_2=np.arange(500,531)
print(ar_1)
print(ar_2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517
 518 519 520 521 522 523 524 525 526 527 528 529 530]


In [36]:
np.concatenate([ar_1,ar_2])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

In [ ]:
#8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun.
#Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.


In [38]:
new_ar=np.arange(15,51)
new_ar

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50])

In [39]:
new_ar2=np.arange(10,101)
new_ar2

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [40]:
concat_ar=np.concatenate([new_ar,new_ar2])
concat_ar

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [41]:
concat_ar[25:51]=888
concat_ar

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
#9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5)
#shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.


In [23]:
new_ar1=np.arange(40).reshape(8,5)
new_ar1

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [24]:
new_ar2=np.arange(320,360).reshape(8,5)
new_ar2

[[320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]


In [25]:
np.concatenate([new_ar1,new_ar2],axis=0) 

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [26]:
np.concatenate([new_ar1,new_ar2],axis=1)  

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

In [ ]:
#10) 9.Soruda oluşturduğunuz 2 array'i sutunlara gore stacklemeye(yığınlamaya) çalışın.


In [61]:
np.stack([new_ar1,new_ar2],axis=1)

array([[[  0,   1,   2,   3,   4],
        [320, 321, 322, 323, 324]],

       [[  5,   6,   7,   8,   9],
        [325, 326, 327, 328, 329]],

       [[ 10,  11,  12,  13,  14],
        [330, 331, 332, 333, 334]],

       [[ 15,  16,  17,  18,  19],
        [335, 336, 337, 338, 339]],

       [[ 20,  21,  22,  23,  24],
        [340, 341, 342, 343, 344]],

       [[ 25,  26,  27,  28,  29],
        [345, 346, 347, 348, 349]],

       [[ 30,  31,  32,  33,  34],
        [350, 351, 352, 353, 354]],

       [[ 35,  36,  37,  38,  39],
        [355, 356, 357, 358, 359]]])

In [ ]:
#11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e 
#eşit olan değerlerin indexleri bulun.


In [63]:
arr=np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(arr==5)

(array([ 5, 13], dtype=int64),)

In [ ]:
#12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.


In [64]:
np.where(arr%2==0)

(array([ 1,  3,  4,  6,  7,  9, 11], dtype=int64),)

In [ ]:
#13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.


In [65]:
np.where(arr>4)

(array([ 1,  2,  5,  9, 10, 11, 13], dtype=int64),)

In [ ]:
#14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.


In [66]:
np.where(arr%5==0)

(array([ 1,  2,  5, 13], dtype=int64),)

In [ ]:
#15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin


In [80]:
arr=np.arange(85,101)
np.random.choice(arr)

88

In [74]:
#16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.


In [99]:
arr=np.arange(10,100)

np.random.choice(arr,9).reshape(3,3)  #ve ya np.random.randint(10,100,9).reshape(3,3)

array([[85, 16, 45],
       [90, 68, 21],
       [25, 44, 63]])

In [ ]:
#17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.


In [108]:
arr=np.arange(35,60)
np.random.choice(arr)

58

In [107]:
#18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.


In [29]:
arr=np.array([3,8,10,53])
np.random.choice(arr,10).reshape(2,5)

array([[10,  8, 53,  3, 10],
       [53,  3, 10,  8,  3]])